---
abstract: 'Hash access to Lingua::EN::Numbers objects.'
author:
  - 'Abigail <lingua-en-numbers-easy@abigail.be>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
keywords: []
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-EN-Numbers-Easy
no_index:
  directory:
    - t
    - inc
requires:
  Lingua::EN::Numbers: 1.01
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/Abigail/lingua--en--numbers--easy.git
version: 2014120401
x_test_requires:
  strict: 0
  warnings: 0
